name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      CI: true
      SSHOOGR_RELEASE: true
      SECRETHUB_CREDENTIAL: ${{ secrets.SECRETHUB_CREDENTIAL }}
      GRGIT_USER: ${{ secrets.SSHOOGR_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-cache-${{ hashFiles('**/*.gradle') }}-${{ hashFiles('**/gradle.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Cache gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradlew') }}
          restore-keys: |
            ${{ runner.os }}-gradlew-

      - name: Setup credentials
        run: |
          sudo echo "deb [trusted=yes] https://apt.secrethub.io stable main" > secrethub.sources.list
          sudo mv secrethub.sources.list /etc/apt/sources.list.d/secrethub.sources.list
          sudo apt-get update
          sudo apt-get install -y secrethub-cli
          mkdir -p $HOME/.gradle
          secrethub read sshoogr/sshoogr/secring.gpg -o secring.gpg
          truncate --size=-1 secring.gpg
          secrethub inject -i .github/gradle.properties.tmpl > $HOME/.gradle/gradle.properties

      - name: Release
        run: |
          chmod +x gradlew
          ./gradlew publishPlugins